services:
  postgres:
    image: postgres:16-alpine
    container_name: labtelemetry_postgres
    environment:
      POSTGRES_DB: labtelemetry
      POSTGRES_USER: labtelemetry
      POSTGRES_PASSWORD: labtelemetry_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: labtelemetry_jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    restart: unless-stopped

volumes:
  pgdata:
