# Generated by Django 5.2.9 on 2026-06-07 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetrySensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parameter', models.CharField(choices=[('PH', 'Potencial Hidrogeniônico'), ('TURBIDITY', 'Turbidez (NTU)'), ('TOC', 'Carbono Orgânico Total')], max_length=20)),
                ('status', models.CharField(choices=[('HEALTHY', 'Saudável'), ('DRIFTING', 'Desvio Detectado (Drift)'), ('FAILED', 'Falha de Sinal')], default='HEALTHY', max_length=20)),
                ('calibration_factor', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelemetryReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('raw_value', models.FloatField()),
                ('calibrated_value', models.FloatField()),
                ('status', models.CharField(choices=[('NORMAL', 'Normal'), ('OUT_OF_BOUNDS', 'Fora dos Limites de Processo'), ('DRIFT_WARNING', 'Alerta de Desvio de Calibração')], default='NORMAL', max_length=20)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='telemetry.telemetrysensor')),
            ],
        ),
        migrations.CreateModel(
            name='TelemetryAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='telemetry.telemetrysensor')),
            ],
        ),
    ]
