# Generated by Django 5.2.9 on 2026-06-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='telemetryreading',
            index=models.Index(fields=['sensor', 'timestamp'], name='telemetry_t_sensor__0d3d32_idx'),
        ),
    ]
