# Generated by Django 5.2.9 on 2026-06-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_telemetryreading_telemetry_t_sensor__0d3d32_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetryreading',
            name='source',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
