# Generated by Django 5.2.9 on 2026-07-11 19:15

from django.db import migrations, models
from django.db.models import Min


def dedupe_readings(apps, schema_editor):
    """Remove duplicatas de (sensor, timestamp) antes de aplicar a constraint.

    Sem isto, a AddConstraint abaixo falha com UniqueViolation em qualquer
    banco que ja tenha dados gravados pela versao anterior — que nao tinha a
    constraint e portanto permitia duplicatas. O sintoma e brutal em Docker:
    o entrypoint roda `migrate`, o migrate falha, o gunicorn nunca sobe e o
    container entra em crash loop. Instalacao nova nunca reproduz, e por isso
    o CI (banco sempre vazio) nao pegava.

    Politica: mantem a linha de menor id em cada grupo, ou seja, a primeira
    observacao gravada. E a mesma semantica que a ingestao passou a ter com
    `bulk_create(ignore_conflicts=True)`: quem chegou primeiro vence.
    """
    TelemetryReading = apps.get_model("telemetry", "TelemetryReading")

    # ponytail: materializa os ids a manter numa lista. Para a escala deste
    # lab isso e irrelevante; se a tabela crescer para milhoes de linhas,
    # trocar por um DELETE ... USING em SQL puro.
    keep_ids = list(
        TelemetryReading.objects.values("sensor_id", "timestamp")
        .annotate(keep_id=Min("id"))
        .values_list("keep_id", flat=True)
    )

    if keep_ids:
        TelemetryReading.objects.exclude(id__in=keep_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0003_telemetryreading_source'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='telemetryreading',
            name='telemetry_t_sensor__0d3d32_idx',
        ),
        migrations.RunPython(dedupe_readings, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='telemetryreading',
            constraint=models.UniqueConstraint(fields=('sensor', 'timestamp'), name='uq_sensor_timestamp'),
        ),
    ]
