# Generated by Django 5.2.9 on 2026-07-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0003_telemetryreading_source'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='telemetryreading',
            name='telemetry_t_sensor__0d3d32_idx',
        ),
        migrations.AddConstraint(
            model_name='telemetryreading',
            constraint=models.UniqueConstraint(fields=('sensor', 'timestamp'), name='uq_sensor_timestamp'),
        ),
    ]
